apiVersion: apps/v1
kind: Deployment

metadata:
  name: employee-app

spec:
  replicas: 3

  selector:
    matchLabels:
      app: employee-app

  template:
    metadata:
      labels:
        app: employee-app

    spec:
      containers:
      - name: employee-container
        image: employee-app:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000