trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: employee-app
  tag: $(Build.BuildId)

steps:

- checkout: self

- script: |
    python3 -m pip install -r requirements.txt
  displayName: Install Dependencies

- task: Docker@2
  displayName: Build and Push Image
  inputs:
    command: buildAndPush
    containerRegistry: 'ACR-Docker'
    repository: 'employee-app'
    dockerfile: 'Dockerfile'
    tags: |
      $(tag)
      latest

- task: KubernetesManifest@1
  displayName: Deploy to AKS
  inputs:
    action: deploy
    kubernetesServiceConnection: 'AKS Service Connection'
    namespace: default
    manifests: |
      k8s/deployment.yaml
      k8s/service.yaml