- task: KubernetesManifest@1
  displayName: Deploy to AKS
  inputs:
    action: deploy
    kubernetesServiceConnection: 'AKS Service Connection'
    namespace: default
    manifests: |
      k8s/deployment.yaml
      k8s/service.yaml
    containers: |
      dhevaemployeeacr.azurecr.io/employee-app:$(tag)